# Generated by Django 4.0.6 on 2022-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
